# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity'),
        ),
    ]
