# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='data',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
