# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for Trako CLI."""

import os

block_cipher = None

a = Analysis(
    ["cli/entry.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=[
        "cli",
        "cli.main",
        "cli.commands",
        "cli.commands.health",
        "cli.commands.auth",
        "cli.commands.config",
        "cli.commands.account",
        "cli.commands.category",
        "cli.commands.contact",
        "cli.commands.user",
        "cli.commands.transaction",
        "cli.commands.budget",
        "cli.commands.currency",
        "cli.commands.split",
        "cli.commands.stats",
        "cli.commands.misc",
        "cli.commands.db",
        "cli.commands.completion",
        "cli.core",
        "cli.core.api",
        "cli.core.config",
        "cli.core.output",
        "cli.utils",
        "cli.utils.dates",
        "cli.utils.formatting",
        "cli.utils.lookups",
        "cli.utils.prompts",
        "tracko_sdk",
        "tracko_sdk.api",
        "tracko_sdk.models",
        "tracko_sdk.rest",
        "tracko_sdk.api_client",
        "tracko_sdk.configuration",
        "tracko_sdk.exceptions",
        "typer",
        "click",
        "rich",
        "pydantic",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="trako",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
