version: '3'
services:
  web:
    build: .
    container_name: tracko_java_spring
    links:
      - db
    environment:
      DBHOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres_local
    image: postgres
    restart: always
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: expense_manager
      POSTGRES_PASSWORD: root

  jenkins-local:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 5000:5000



volumes:
  postgresvolume: