# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.stats_controller_api import StatsControllerApi


class TestStatsControllerApi(unittest.TestCase):
    """StatsControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatsControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_category_stats(self) -> None:
        """Test case for get_category_stats

        """
        pass

    def test_get_stats(self) -> None:
        """Test case for get_stats

        """
        pass


if __name__ == '__main__':
    unittest.main()
