# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.transaction_history_api import TransactionHistoryApi


class TestTransactionHistoryApi(unittest.TestCase):
    """TransactionHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_history(self) -> None:
        """Test case for get_all_history

        List transaction change history (paged) across all transactions
        """
        pass

    def test_get_history(self) -> None:
        """Test case for get_history

        Get a transaction's change history
        """
        pass

    def test_get_trash(self) -> None:
        """Test case for get_trash

        List deleted transactions (recycle bin)
        """
        pass

    def test_revert(self) -> None:
        """Test case for revert

        Revert a transaction to a history snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
