# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.account_controller_api import AccountControllerApi


class TestAccountControllerApi(unittest.TestCase):
    """AccountControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create7(self) -> None:
        """Test case for create7

        """
        pass

    def test_delete7(self) -> None:
        """Test case for delete7

        """
        pass

    def test_get_account_monthly_summaries(self) -> None:
        """Test case for get_account_monthly_summaries

        """
        pass

    def test_get_account_summary(self) -> None:
        """Test case for get_account_summary

        """
        pass

    def test_get_account_transactions(self) -> None:
        """Test case for get_account_transactions

        """
        pass

    def test_get_account_yearly_summaries(self) -> None:
        """Test case for get_account_yearly_summaries

        """
        pass

    def test_get_all6(self) -> None:
        """Test case for get_all6

        """
        pass

    def test_get_by_id4(self) -> None:
        """Test case for get_by_id4

        """
        pass

    def test_get_my_account_balances(self) -> None:
        """Test case for get_my_account_balances

        """
        pass

    def test_update5(self) -> None:
        """Test case for update5

        """
        pass


if __name__ == '__main__':
    unittest.main()
