# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.budget_api import BudgetApi


class TestBudgetApi(unittest.TestCase):
    """BudgetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetApi()

    def tearDown(self) -> None:
        pass

    def test_allocate_funds(self) -> None:
        """Test case for allocate_funds

        Allocate funds to a category for a month
        """
        pass

    def test_get_available_to_assign(self) -> None:
        """Test case for get_available_to_assign

        Get the amount available to assign for a month
        """
        pass

    def test_get_budget(self) -> None:
        """Test case for get_budget

        Get budget details for a month/year
        """
        pass

    def test_get_current_budget(self) -> None:
        """Test case for get_current_budget

        Get budget for the current month
        """
        pass


if __name__ == '__main__':
    unittest.main()
