# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.account_save_request import AccountSaveRequest

class TestAccountSaveRequest(unittest.TestCase):
    """AccountSaveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountSaveRequest:
        """Test AccountSaveRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountSaveRequest`
        """
        model = AccountSaveRequest()
        if include_optional:
            return AccountSaveRequest(
                name = '',
                currency = 'EIO'
            )
        else:
            return AccountSaveRequest(
                name = '',
        )
        """

    def testAccountSaveRequest(self):
        """Test AccountSaveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
