# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.exchange_rates_api import ExchangeRatesApi


class TestExchangeRatesApi(unittest.TestCase):
    """ExchangeRatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExchangeRatesApi()

    def tearDown(self) -> None:
        pass

    def test_get_rates(self) -> None:
        """Test case for get_rates

        Get exchange rates for a base currency (e.g. USD)
        """
        pass


if __name__ == '__main__':
    unittest.main()
