# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_rates200_response import GetRates200Response

class TestGetRates200Response(unittest.TestCase):
    """GetRates200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRates200Response:
        """Test GetRates200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRates200Response`
        """
        model = GetRates200Response()
        if include_optional:
            return GetRates200Response(
                result = tracko_sdk.models.exchange_rate_api_response.ExchangeRateApiResponse(
                    base_code = '', 
                    rates = {
                        'key' : 1.337
                        }, ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetRates200Response(
        )
        """

    def testGetRates200Response(self):
        """Test GetRates200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
