# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.json_store_controller_api import JsonStoreControllerApi


class TestJsonStoreControllerApi(unittest.TestCase):
    """JsonStoreControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JsonStoreControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create4(self) -> None:
        """Test case for create4

        """
        pass

    def test_delete4(self) -> None:
        """Test case for delete4

        """
        pass

    def test_get_all4(self) -> None:
        """Test case for get_all4

        """
        pass

    def test_get_by_name(self) -> None:
        """Test case for get_by_name

        """
        pass

    def test_update2(self) -> None:
        """Test case for update2

        """
        pass


if __name__ == '__main__':
    unittest.main()
