# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.transactions_page_dto import TransactionsPageDTO

class TestTransactionsPageDTO(unittest.TestCase):
    """TransactionsPageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsPageDTO:
        """Test TransactionsPageDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsPageDTO`
        """
        model = TransactionsPageDTO()
        if include_optional:
            return TransactionsPageDTO(
                month = 56,
                year = 56,
                page = 56,
                size = 56,
                total_elements = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True,
                transactions = [
                    None
                    ]
            )
        else:
            return TransactionsPageDTO(
        )
        """

    def testTransactionsPageDTO(self):
        """Test TransactionsPageDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
