# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.recurring_transaction_controller_api import RecurringTransactionControllerApi


class TestRecurringTransactionControllerApi(unittest.TestCase):
    """RecurringTransactionControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecurringTransactionControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create3(self) -> None:
        """Test case for create3

        """
        pass

    def test_delete3(self) -> None:
        """Test case for delete3

        """
        pass

    def test_get_all3(self) -> None:
        """Test case for get_all3

        """
        pass

    def test_get_by_id2(self) -> None:
        """Test case for get_by_id2

        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        """
        pass


if __name__ == '__main__':
    unittest.main()
