# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.statistics_api import StatisticsApi


class TestStatisticsApi(unittest.TestCase):
    """StatisticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatisticsApi()

    def tearDown(self) -> None:
        pass

    def test_get_category_stats(self) -> None:
        """Test case for get_category_stats

        Get stats for a specific category by range
        """
        pass

    def test_get_stats(self) -> None:
        """Test case for get_stats

        Get aggregated stats by range (weekly/monthly/yearly/custom)
        """
        pass


if __name__ == '__main__':
    unittest.main()
