# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.list_mine200_response import ListMine200Response

class TestListMine200Response(unittest.TestCase):
    """ListMine200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMine200Response:
        """Test ListMine200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMine200Response`
        """
        model = ListMine200Response()
        if include_optional:
            return ListMine200Response(
                result = [
                    tracko_sdk.models.contact.Contact(
                        id = 56, 
                        user_id = '', 
                        name = '', 
                        phone_no = '', 
                        email = '', )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return ListMine200Response(
        )
        """

    def testListMine200Response(self):
        """Test ListMine200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
