# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.stats_point_dto import StatsPointDTO

class TestStatsPointDTO(unittest.TestCase):
    """StatsPointDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsPointDTO:
        """Test StatsPointDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsPointDTO`
        """
        model = StatsPointDTO()
        if include_optional:
            return StatsPointDTO(
                label = '',
                value = 1.337
            )
        else:
            return StatsPointDTO(
        )
        """

    def testStatsPointDTO(self):
        """Test StatsPointDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
