# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.budget_allocation_request_dto import BudgetAllocationRequestDTO

class TestBudgetAllocationRequestDTO(unittest.TestCase):
    """BudgetAllocationRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetAllocationRequestDTO:
        """Test BudgetAllocationRequestDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BudgetAllocationRequestDTO`
        """
        model = BudgetAllocationRequestDTO()
        if include_optional:
            return BudgetAllocationRequestDTO(
                month = 56,
                year = 56,
                category_id = 56,
                amount = 1.337
            )
        else:
            return BudgetAllocationRequestDTO(
                month = 56,
                year = 56,
                category_id = 56,
                amount = 1.337,
        )
        """

    def testBudgetAllocationRequestDTO(self):
        """Test BudgetAllocationRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
