# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_chart_data200_response import GetChartData200Response

class TestGetChartData200Response(unittest.TestCase):
    """GetChartData200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChartData200Response:
        """Test GetChartData200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChartData200Response`
        """
        model = GetChartData200Response()
        if include_optional:
            return GetChartData200Response(
                result = tracko_sdk.models.analytics_response_dto.AnalyticsResponseDTO(
                    granularity = '', 
                    transaction_type = '1', 
                    period_start = '', 
                    period_end = '', 
                    total = 1.337, 
                    grouped_series = [
                        tracko_sdk.models.named_series_dto.NamedSeriesDTO(
                            name = '', 
                            series = [
                                tracko_sdk.models.stats_point_dto.StatsPointDTO(
                                    label = '', 
                                    value = 1.337, )
                                ], )
                        ], ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetChartData200Response(
        )
        """

    def testGetChartData200Response(self):
        """Test GetChartData200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
