# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_history200_response import GetHistory200Response

class TestGetHistory200Response(unittest.TestCase):
    """GetHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHistory200Response:
        """Test GetHistory200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHistory200Response`
        """
        model = GetHistory200Response()
        if include_optional:
            return GetHistory200Response(
                result = [
                    tracko_sdk.models.transaction_history_dto.TransactionHistoryDTO(
                        id = 56, 
                        transaction_id = 56, 
                        operation = '', 
                        changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        linked_transaction_id = 56, 
                        name = '', 
                        amount = 1.337, 
                        original_currency = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        transaction_type = 56, )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return GetHistory200Response(
        )
        """

    def testGetHistory200Response(self):
        """Test GetHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
