# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.user_controller_api import UserControllerApi


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        """
        pass

    def test_me(self) -> None:
        """Test case for me

        """
        pass

    def test_reset_data(self) -> None:
        """Test case for reset_data

        """
        pass

    def test_reset_transactions(self) -> None:
        """Test case for reset_transactions

        """
        pass

    def test_show(self) -> None:
        """Test case for show

        """
        pass

    def test_show1(self) -> None:
        """Test case for show1

        """
        pass

    def test_show_by_phone(self) -> None:
        """Test case for show_by_phone

        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        """
        pass


if __name__ == '__main__':
    unittest.main()
