# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_budget200_response import GetBudget200Response

class TestGetBudget200Response(unittest.TestCase):
    """GetBudget200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBudget200Response:
        """Test GetBudget200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBudget200Response`
        """
        model = GetBudget200Response()
        if include_optional:
            return GetBudget200Response(
                result = tracko_sdk.models.budget_response_dto.BudgetResponseDTO(
                    month = 56, 
                    year = 56, 
                    total_budget = 1.337, 
                    total_income = 1.337, 
                    total_spent = 1.337, 
                    rollover_amount = 1.337, 
                    available_to_assign = 1.337, 
                    is_closed = True, 
                    categories = [
                        tracko_sdk.models.budget_category_dto.BudgetCategoryDTO(
                            category_id = 56, 
                            category_name = '', 
                            allocated_amount = 1.337, 
                            actual_spent = 1.337, 
                            remaining_balance = 1.337, )
                        ], ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetBudget200Response(
        )
        """

    def testGetBudget200Response(self):
        """Test GetBudget200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
