# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_create1(self) -> None:
        """Test case for create1

        Create a transaction or transfer
        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        Delete a transaction or transfer
        """
        pass

    def test_get_all1(self) -> None:
        """Test case for get_all1

        List transactions with optional filters
        """
        pass

    def test_get_by_id(self) -> None:
        """Test case for get_by_id

        Get a transaction by ID
        """
        pass

    def test_get_monthly_summaries(self) -> None:
        """Test case for get_monthly_summaries

        Monthly summaries for a year
        """
        pass

    def test_get_my_summary(self) -> None:
        """Test case for get_my_summary

        Get income/expense summary in a date range
        """
        pass

    def test_get_my_total_expense(self) -> None:
        """Test case for get_my_total_expense

        Get total expense in a date range
        """
        pass

    def test_get_my_total_income(self) -> None:
        """Test case for get_my_total_income

        Get total income in a date range
        """
        pass

    def test_get_yearly_summaries(self) -> None:
        """Test case for get_yearly_summaries

        Yearly summaries
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update a transaction or transfer
        """
        pass


if __name__ == '__main__':
    unittest.main()
