# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.transaction_summary_dto import TransactionSummaryDTO

class TestTransactionSummaryDTO(unittest.TestCase):
    """TransactionSummaryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionSummaryDTO:
        """Test TransactionSummaryDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionSummaryDTO`
        """
        model = TransactionSummaryDTO()
        if include_optional:
            return TransactionSummaryDTO(
                total_income = 1.337,
                total_expense = 1.337,
                net_total = 1.337,
                rollover_net = 1.337,
                net_total_with_rollover = 1.337,
                transaction_count = 56
            )
        else:
            return TransactionSummaryDTO(
        )
        """

    def testTransactionSummaryDTO(self):
        """Test TransactionSummaryDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
