# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_by_id200_response import GetById200Response

class TestGetById200Response(unittest.TestCase):
    """GetById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetById200Response:
        """Test GetById200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetById200Response`
        """
        model = GetById200Response()
        if include_optional:
            return GetById200Response(
                result = tracko_sdk.models.transaction.Transaction(
                    id = 56, 
                    name = '', 
                    comments = '', 
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    amount = 1.337, 
                    original_currency = '', 
                    original_amount = 1.337, 
                    exchange_rate = 1.337, 
                    account_id = 56, 
                    category_id = 56, 
                    is_countable = 56, 
                    linked_transaction_id = 56, 
                    transaction_type = 56, ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetById200Response(
        )
        """

    def testGetById200Response(self):
        """Test GetById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
