# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.user_currency import UserCurrency

class TestUserCurrency(unittest.TestCase):
    """UserCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCurrency:
        """Test UserCurrency
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCurrency`
        """
        model = UserCurrency()
        if include_optional:
            return UserCurrency(
                id = 56,
                currency_code = '',
                exchange_rate = 1.337
            )
        else:
            return UserCurrency(
                currency_code = '',
                exchange_rate = 1.337,
        )
        """

    def testUserCurrency(self):
        """Test UserCurrency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
