# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health(self) -> None:
        """Test case for health

        Check service health
        """
        pass


if __name__ == '__main__':
    unittest.main()
