# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.transaction_history_page_dto import TransactionHistoryPageDTO

class TestTransactionHistoryPageDTO(unittest.TestCase):
    """TransactionHistoryPageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionHistoryPageDTO:
        """Test TransactionHistoryPageDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionHistoryPageDTO`
        """
        model = TransactionHistoryPageDTO()
        if include_optional:
            return TransactionHistoryPageDTO(
                page = 56,
                size = 56,
                total_elements = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True,
                history = [
                    tracko_sdk.models.transaction_history_dto.TransactionHistoryDTO(
                        id = 56, 
                        transaction_id = 56, 
                        operation = '', 
                        changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        linked_transaction_id = 56, 
                        name = '', 
                        amount = 1.337, 
                        original_currency = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        transaction_type = 56, )
                    ]
            )
        else:
            return TransactionHistoryPageDTO(
        )
        """

    def testTransactionHistoryPageDTO(self):
        """Test TransactionHistoryPageDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
