# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.delete200_response import Delete200Response

class TestDelete200Response(unittest.TestCase):
    """Delete200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Delete200Response:
        """Test Delete200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Delete200Response`
        """
        model = Delete200Response()
        if include_optional:
            return Delete200Response(
                result = '',
                message = 'Resource retrieved successfully'
            )
        else:
            return Delete200Response(
        )
        """

    def testDelete200Response(self):
        """Test Delete200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
