# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.contact_save_request import ContactSaveRequest

class TestContactSaveRequest(unittest.TestCase):
    """ContactSaveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactSaveRequest:
        """Test ContactSaveRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactSaveRequest`
        """
        model = ContactSaveRequest()
        if include_optional:
            return ContactSaveRequest(
                name = '',
                phone_no = '',
                email = ''
            )
        else:
            return ContactSaveRequest(
                name = '',
        )
        """

    def testContactSaveRequest(self):
        """Test ContactSaveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
