# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_all4200_response import GetAll4200Response

class TestGetAll4200Response(unittest.TestCase):
    """GetAll4200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAll4200Response:
        """Test GetAll4200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAll4200Response`
        """
        model = GetAll4200Response()
        if include_optional:
            return GetAll4200Response(
                result = [
                    tracko_sdk.models.json_store.JsonStore(
                        name = '', 
                        value = '', )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return GetAll4200Response(
        )
        """

    def testGetAll4200Response(self):
        """Test GetAll4200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
