# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.split_controller_api import SplitControllerApi


class TestSplitControllerApi(unittest.TestCase):
    """SplitControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SplitControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create2(self) -> None:
        """Test case for create2

        """
        pass

    def test_delete2(self) -> None:
        """Test case for delete2

        """
        pass

    def test_get_all2(self) -> None:
        """Test case for get_all2

        """
        pass

    def test_get_by_contact_id(self) -> None:
        """Test case for get_by_contact_id

        """
        pass

    def test_get_by_id1(self) -> None:
        """Test case for get_by_id1

        """
        pass

    def test_get_by_transaction_id(self) -> None:
        """Test case for get_by_transaction_id

        """
        pass

    def test_get_my_unsettled(self) -> None:
        """Test case for get_my_unsettled

        """
        pass

    def test_get_unsettled_by_contact_id(self) -> None:
        """Test case for get_unsettled_by_contact_id

        """
        pass

    def test_settle(self) -> None:
        """Test case for settle

        """
        pass

    def test_unsettle(self) -> None:
        """Test case for unsettle

        """
        pass


if __name__ == '__main__':
    unittest.main()
