# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.contact_controller_api import ContactControllerApi


class TestContactControllerApi(unittest.TestCase):
    """ContactControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create5(self) -> None:
        """Test case for create5

        """
        pass

    def test_delete5(self) -> None:
        """Test case for delete5

        """
        pass

    def test_get_one(self) -> None:
        """Test case for get_one

        """
        pass

    def test_list_mine(self) -> None:
        """Test case for list_mine

        """
        pass

    def test_update3(self) -> None:
        """Test case for update3

        """
        pass


if __name__ == '__main__':
    unittest.main()
