# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_create5(self) -> None:
        """Test case for create5

        Create a new contact
        """
        pass

    def test_delete5(self) -> None:
        """Test case for delete5

        Delete a contact
        """
        pass

    def test_get_one(self) -> None:
        """Test case for get_one

        Get a contact by ID
        """
        pass

    def test_list_mine(self) -> None:
        """Test case for list_mine

        List all contacts for the current user
        """
        pass

    def test_update3(self) -> None:
        """Test case for update3

        Update a contact
        """
        pass


if __name__ == '__main__':
    unittest.main()
