# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.session_controller_api import SessionControllerApi


class TestSessionControllerApi(unittest.TestCase):
    """SessionControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionControllerApi()

    def tearDown(self) -> None:
        pass

    def test_login(self) -> None:
        """Test case for login

        """
        pass

    def test_sign_in(self) -> None:
        """Test case for sign_in

        """
        pass


if __name__ == '__main__':
    unittest.main()
