# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_yearly_summaries200_response import GetYearlySummaries200Response

class TestGetYearlySummaries200Response(unittest.TestCase):
    """GetYearlySummaries200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetYearlySummaries200Response:
        """Test GetYearlySummaries200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetYearlySummaries200Response`
        """
        model = GetYearlySummaries200Response()
        if include_optional:
            return GetYearlySummaries200Response(
                result = [
                    tracko_sdk.models.transaction_period_summary_dto.TransactionPeriodSummaryDTO(
                        total_income = 1.337, 
                        total_expense = 1.337, 
                        net_total = 1.337, 
                        rollover_net = 1.337, 
                        net_total_with_rollover = 1.337, 
                        transaction_count = 56, 
                        year = 56, 
                        month = 56, )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return GetYearlySummaries200Response(
        )
        """

    def testGetYearlySummaries200Response(self):
        """Test GetYearlySummaries200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
