# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.transaction_search_hit_dto import TransactionSearchHitDTO

class TestTransactionSearchHitDTO(unittest.TestCase):
    """TransactionSearchHitDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionSearchHitDTO:
        """Test TransactionSearchHitDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionSearchHitDTO`
        """
        model = TransactionSearchHitDTO()
        if include_optional:
            return TransactionSearchHitDTO(
                transaction = tracko_sdk.models.transaction_detail_dto.TransactionDetailDTO(
                    id = 56, 
                    transaction_type = 56, 
                    name = '', 
                    comments = '', 
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    amount = 1.337, 
                    original_currency = '', 
                    original_amount = 1.337, 
                    exchange_rate = 1.337, 
                    account_id = 56, 
                    category_id = 56, 
                    is_countable = 56, 
                    category = tracko_sdk.models.category.Category(
                        id = 56, 
                        name = '', 
                        user_id = '', 
                        is_roll_over_enabled = True, 
                        parent_category_id = 56, 
                        category_type = 'INCOME', ), 
                    account = tracko_sdk.models.account.Account(
                        id = 56, 
                        name = '', 
                        user_id = '', 
                        currency = '', 
                        balance = 1.337, ), 
                    splits = [
                        tracko_sdk.models.split_detail_dto.SplitDetailDTO(
                            split = tracko_sdk.models.split.Split(
                                id = 56, 
                                transaction_id = 56, 
                                user_id = '', 
                                amount = 1.337, 
                                settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                is_settled = 56, 
                                contact_id = 56, ), 
                            contact = tracko_sdk.models.contact.Contact(
                                id = 56, 
                                user_id = '', 
                                name = '', 
                                phone_no = '', 
                                email = '', ), )
                        ], ),
                relevance_score = 1.337,
                highlights = {
                    'key' : ''
                    },
                matched_fields = [
                    ''
                    ]
            )
        else:
            return TransactionSearchHitDTO(
        )
        """

    def testTransactionSearchHitDTO(self):
        """Test TransactionSearchHitDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
