# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_by_id3200_response import GetById3200Response

class TestGetById3200Response(unittest.TestCase):
    """GetById3200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetById3200Response:
        """Test GetById3200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetById3200Response`
        """
        model = GetById3200Response()
        if include_optional:
            return GetById3200Response(
                result = tracko_sdk.models.category.Category(
                    id = 56, 
                    name = '', 
                    user_id = '', 
                    is_roll_over_enabled = True, 
                    parent_category_id = 56, 
                    category_type = 'INCOME', ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetById3200Response(
        )
        """

    def testGetById3200Response(self):
        """Test GetById3200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
