# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.exchange_rate_controller_api import ExchangeRateControllerApi


class TestExchangeRateControllerApi(unittest.TestCase):
    """ExchangeRateControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExchangeRateControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_rates(self) -> None:
        """Test case for get_rates

        """
        pass


if __name__ == '__main__':
    unittest.main()
