# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_create7(self) -> None:
        """Test case for create7

        Create a new account
        """
        pass

    def test_delete7(self) -> None:
        """Test case for delete7

        Delete an account
        """
        pass

    def test_get_account_monthly_summaries(self) -> None:
        """Test case for get_account_monthly_summaries

        Get monthly summaries for an account
        """
        pass

    def test_get_account_summary(self) -> None:
        """Test case for get_account_summary

        Get income/expense summary for an account in a date range
        """
        pass

    def test_get_account_transactions(self) -> None:
        """Test case for get_account_transactions

        List transactions for an account with optional filters
        """
        pass

    def test_get_account_yearly_summaries(self) -> None:
        """Test case for get_account_yearly_summaries

        Get yearly summaries for an account
        """
        pass

    def test_get_all6(self) -> None:
        """Test case for get_all6

        List all accounts for the current user
        """
        pass

    def test_get_by_id4(self) -> None:
        """Test case for get_by_id4

        Get an account by ID
        """
        pass

    def test_get_my_account_balances(self) -> None:
        """Test case for get_my_account_balances

        Get balances for all accounts (derived from transactions)
        """
        pass

    def test_update5(self) -> None:
        """Test case for update5

        Update an account
        """
        pass


if __name__ == '__main__':
    unittest.main()
