# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.allocate_funds200_response import AllocateFunds200Response

class TestAllocateFunds200Response(unittest.TestCase):
    """AllocateFunds200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllocateFunds200Response:
        """Test AllocateFunds200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllocateFunds200Response`
        """
        model = AllocateFunds200Response()
        if include_optional:
            return AllocateFunds200Response(
                result = tracko_sdk.models.budget_category_dto.BudgetCategoryDTO(
                    category_id = 56, 
                    category_name = '', 
                    allocated_amount = 1.337, 
                    actual_spent = 1.337, 
                    remaining_balance = 1.337, ),
                message = 'Resource retrieved successfully'
            )
        else:
            return AllocateFunds200Response(
        )
        """

    def testAllocateFunds200Response(self):
        """Test AllocateFunds200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
