# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_all200_response import GetAll200Response

class TestGetAll200Response(unittest.TestCase):
    """GetAll200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAll200Response:
        """Test GetAll200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAll200Response`
        """
        model = GetAll200Response()
        if include_optional:
            return GetAll200Response(
                result = [
                    tracko_sdk.models.user_currency.UserCurrency(
                        id = 56, 
                        currency_code = '', 
                        exchange_rate = 1.337, )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return GetAll200Response(
        )
        """

    def testGetAll200Response(self):
        """Test GetAll200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
