# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.me200_response import Me200Response

class TestMe200Response(unittest.TestCase):
    """Me200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Me200Response:
        """Test Me200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Me200Response`
        """
        model = Me200Response()
        if include_optional:
            return Me200Response(
                result = tracko_sdk.models.user.User(
                    id = '', 
                    name = '', 
                    phone_no = '', 
                    email = '', 
                    profile_pic = '', 
                    password = '', 
                    global_id = '', 
                    base_currency = '', 
                    is_shadow = 56, 
                    is_admin = 56, 
                    secondary_currencies = [
                        tracko_sdk.models.user_currency.UserCurrency(
                            id = 56, 
                            currency_code = '', 
                            exchange_rate = 1.337, )
                        ], 
                    shadow = True, 
                    admin = True, ),
                message = 'Resource retrieved successfully'
            )
        else:
            return Me200Response(
        )
        """

    def testMe200Response(self):
        """Test Me200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
