# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.user_save_request import UserSaveRequest

class TestUserSaveRequest(unittest.TestCase):
    """UserSaveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSaveRequest:
        """Test UserSaveRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSaveRequest`
        """
        model = UserSaveRequest()
        if include_optional:
            return UserSaveRequest(
                name = '',
                phone_no = '',
                email = '',
                profile_pic = '',
                is_shadow = 56,
                base_currency = 'EIO',
                shadow = True,
                password = '0123'
            )
        else:
            return UserSaveRequest(
                phone_no = '',
                password = '0123',
        )
        """

    def testUserSaveRequest(self):
        """Test UserSaveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
