# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.user_currencies_api import UserCurrenciesApi


class TestUserCurrenciesApi(unittest.TestCase):
    """UserCurrenciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserCurrenciesApi()

    def tearDown(self) -> None:
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Remove a currency from the current user
        """
        pass

    def test_get_all(self) -> None:
        """Test case for get_all

        List currencies configured for the current user
        """
        pass

    def test_save(self) -> None:
        """Test case for save

        Add or update a currency with a manual exchange rate
        """
        pass

    def test_save_auto(self) -> None:
        """Test case for save_auto

        Add a currency with an automatically fetched exchange rate
        """
        pass


if __name__ == '__main__':
    unittest.main()
