# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_one200_response import GetOne200Response

class TestGetOne200Response(unittest.TestCase):
    """GetOne200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOne200Response:
        """Test GetOne200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOne200Response`
        """
        model = GetOne200Response()
        if include_optional:
            return GetOne200Response(
                result = tracko_sdk.models.contact.Contact(
                    id = 56, 
                    user_id = '', 
                    name = '', 
                    phone_no = '', 
                    email = '', ),
                message = 'Resource retrieved successfully'
            )
        else:
            return GetOne200Response(
        )
        """

    def testGetOne200Response(self):
        """Test GetOne200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
