# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.show200_response import Show200Response

class TestShow200Response(unittest.TestCase):
    """Show200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Show200Response:
        """Test Show200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Show200Response`
        """
        model = Show200Response()
        if include_optional:
            return Show200Response(
                result = [
                    tracko_sdk.models.user.User(
                        id = '', 
                        name = '', 
                        phone_no = '', 
                        email = '', 
                        profile_pic = '', 
                        global_id = '', 
                        base_currency = '', 
                        is_shadow = 56, 
                        is_admin = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        secondary_currencies = [
                            tracko_sdk.models.user_currency.UserCurrency(
                                id = 56, 
                                currency_code = '', 
                                exchange_rate = 1.337, )
                            ], 
                        admin = True, 
                        shadow = True, )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return Show200Response(
        )
        """

    def testShow200Response(self):
        """Test Show200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
