# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.get_all6200_response import GetAll6200Response

class TestGetAll6200Response(unittest.TestCase):
    """GetAll6200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAll6200Response:
        """Test GetAll6200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAll6200Response`
        """
        model = GetAll6200Response()
        if include_optional:
            return GetAll6200Response(
                result = [
                    tracko_sdk.models.account.Account(
                        id = 56, 
                        name = '', 
                        user_id = '', 
                        currency = '', 
                        balance = 1.337, )
                    ],
                message = 'Resource retrieved successfully'
            )
        else:
            return GetAll6200Response(
        )
        """

    def testGetAll6200Response(self):
        """Test GetAll6200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
