# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.json_store_api import JSONStoreApi


class TestJSONStoreApi(unittest.TestCase):
    """JSONStoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JSONStoreApi()

    def tearDown(self) -> None:
        pass

    def test_create4(self) -> None:
        """Test case for create4

        Create a JSON store entry
        """
        pass

    def test_delete4(self) -> None:
        """Test case for delete4

        Delete a JSON store entry by name
        """
        pass

    def test_get_all4(self) -> None:
        """Test case for get_all4

        List all JSON store entries
        """
        pass

    def test_get_by_name(self) -> None:
        """Test case for get_by_name

        Get a JSON store entry by name
        """
        pass

    def test_update2(self) -> None:
        """Test case for update2

        Update a JSON store entry by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
