# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.splits_api import SplitsApi


class TestSplitsApi(unittest.TestCase):
    """SplitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SplitsApi()

    def tearDown(self) -> None:
        pass

    def test_create2(self) -> None:
        """Test case for create2

        Create a split for a transaction
        """
        pass

    def test_delete2(self) -> None:
        """Test case for delete2

        Delete a split
        """
        pass

    def test_get_all2(self) -> None:
        """Test case for get_all2

        List all splits for the current user
        """
        pass

    def test_get_by_contact_id(self) -> None:
        """Test case for get_by_contact_id

        List all splits for a contact
        """
        pass

    def test_get_by_id1(self) -> None:
        """Test case for get_by_id1

        Get a split by ID
        """
        pass

    def test_get_by_transaction_id(self) -> None:
        """Test case for get_by_transaction_id

        List splits for a transaction
        """
        pass

    def test_get_my_unsettled(self) -> None:
        """Test case for get_my_unsettled

        List all unsettled splits for the current user
        """
        pass

    def test_get_unsettled_by_contact_id(self) -> None:
        """Test case for get_unsettled_by_contact_id

        List unsettled splits for a contact
        """
        pass

    def test_settle(self) -> None:
        """Test case for settle

        Mark a split as settled
        """
        pass

    def test_unsettle(self) -> None:
        """Test case for unsettle

        Reverse a settlement on a split
        """
        pass


if __name__ == '__main__':
    unittest.main()
