# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.models.exchange_rate_api_response import ExchangeRateApiResponse

class TestExchangeRateApiResponse(unittest.TestCase):
    """ExchangeRateApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeRateApiResponse:
        """Test ExchangeRateApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeRateApiResponse`
        """
        model = ExchangeRateApiResponse()
        if include_optional:
            return ExchangeRateApiResponse(
                base_code = '',
                rates = {
                    'key' : 1.337
                    }
            )
        else:
            return ExchangeRateApiResponse(
        )
        """

    def testExchangeRateApiResponse(self):
        """Test ExchangeRateApiResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
