# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tracko_sdk.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create a new user (admin only)
        """
        pass

    def test_me(self) -> None:
        """Test case for me

        Get the current user's profile
        """
        pass

    def test_reset_data(self) -> None:
        """Test case for reset_data

        Reset all user data (accounts, categories, transactions)
        """
        pass

    def test_reset_transactions(self) -> None:
        """Test case for reset_transactions

        Reset only transactions for the current user
        """
        pass

    def test_show(self) -> None:
        """Test case for show

        List users (admin) or get a user by ID
        """
        pass

    def test_show1(self) -> None:
        """Test case for show1

        List users (admin) or get a user by ID
        """
        pass

    def test_show_by_phone(self) -> None:
        """Test case for show_by_phone

        Look up a user by phone number
        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        Update the current user's profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
