# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20190318_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'Ternary')], default=0),
            preserve_default=False,
        ),
    ]
