# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_entity_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apis.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
