# Generated by Django 2.2 on 2019-06-30 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apis', '0006_auto_20190414_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Entity'),
        ),
    ]
