# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from tracko_sdk.models.named_series_dto import NamedSeriesDTO
from typing import Optional, Set
from typing_extensions import Self

class AnalyticsResponseDTO(BaseModel):
    """
    AnalyticsResponseDTO
    """ # noqa: E501
    granularity: Optional[StrictStr] = None
    transaction_type: Optional[StrictStr] = Field(default=None, alias="transactionType")
    period_start: Optional[StrictStr] = Field(default=None, alias="periodStart")
    period_end: Optional[StrictStr] = Field(default=None, alias="periodEnd")
    total: Optional[Union[StrictFloat, StrictInt]] = None
    grouped_series: Optional[List[NamedSeriesDTO]] = Field(default=None, alias="groupedSeries")
    __properties: ClassVar[List[str]] = ["granularity", "transactionType", "periodStart", "periodEnd", "total", "groupedSeries"]

    @field_validator('transaction_type')
    def transaction_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['1', '2', '3']):
            raise ValueError("must be one of enum values ('1', '2', '3')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyticsResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in grouped_series (list)
        _items = []
        if self.grouped_series:
            for _item in self.grouped_series:
                if _item:
                    _items.append(_item.to_dict())
            _dict['groupedSeries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyticsResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "granularity": obj.get("granularity"),
            "transactionType": obj.get("transactionType"),
            "periodStart": obj.get("periodStart"),
            "periodEnd": obj.get("periodEnd"),
            "total": obj.get("total"),
            "groupedSeries": [NamedSeriesDTO.from_dict(_item) for _item in obj["groupedSeries"]] if obj.get("groupedSeries") is not None else None
        })
        return _obj


