# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from tracko_sdk.models.budget_category_dto import BudgetCategoryDTO
from typing import Optional, Set
from typing_extensions import Self

class BudgetResponseDTO(BaseModel):
    """
    BudgetResponseDTO
    """ # noqa: E501
    month: Optional[StrictInt] = None
    year: Optional[StrictInt] = None
    total_budget: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalBudget")
    total_income: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalIncome")
    total_spent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalSpent")
    rollover_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="rolloverAmount")
    available_to_assign: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="availableToAssign")
    is_closed: Optional[StrictBool] = Field(default=None, alias="isClosed")
    categories: Optional[List[BudgetCategoryDTO]] = None
    __properties: ClassVar[List[str]] = ["month", "year", "totalBudget", "totalIncome", "totalSpent", "rolloverAmount", "availableToAssign", "isClosed", "categories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in categories (list)
        _items = []
        if self.categories:
            for _item in self.categories:
                if _item:
                    _items.append(_item.to_dict())
            _dict['categories'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "month": obj.get("month"),
            "year": obj.get("year"),
            "totalBudget": obj.get("totalBudget"),
            "totalIncome": obj.get("totalIncome"),
            "totalSpent": obj.get("totalSpent"),
            "rolloverAmount": obj.get("rolloverAmount"),
            "availableToAssign": obj.get("availableToAssign"),
            "isClosed": obj.get("isClosed"),
            "categories": [BudgetCategoryDTO.from_dict(_item) for _item in obj["categories"]] if obj.get("categories") is not None else None
        })
        return _obj


