# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Category(BaseModel):
    """
    Category
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: StrictStr
    user_id: StrictStr = Field(alias="userId")
    is_roll_over_enabled: Optional[StrictBool] = Field(default=None, alias="isRollOverEnabled")
    parent_category_id: Optional[StrictInt] = Field(default=None, alias="parentCategoryId")
    category_type: StrictStr = Field(alias="categoryType")
    __properties: ClassVar[List[str]] = ["id", "name", "userId", "isRollOverEnabled", "parentCategoryId", "categoryType"]

    @field_validator('category_type')
    def category_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['INCOME', 'EXPENSE']):
            raise ValueError("must be one of enum values ('INCOME', 'EXPENSE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Category from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Category from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "userId": obj.get("userId"),
            "isRollOverEnabled": obj.get("isRollOverEnabled"),
            "parentCategoryId": obj.get("parentCategoryId"),
            "categoryType": obj.get("categoryType")
        })
        return _obj


