# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RecurringTransaction(BaseModel):
    """
    RecurringTransaction
    """ # noqa: E501
    id: Optional[StrictInt] = None
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    name: Annotated[str, Field(min_length=0, strict=True, max_length=128)]
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    original_currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(alias="originalCurrency")
    original_amount: Union[StrictFloat, StrictInt] = Field(alias="originalAmount")
    exchange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exchangeRate")
    account_id: StrictInt = Field(alias="accountId")
    category_id: StrictInt = Field(alias="categoryId")
    to_account_id: Optional[StrictInt] = Field(default=None, alias="toAccountId")
    transaction_type: StrictStr = Field(alias="transactionType")
    frequency: StrictStr
    start_date: datetime = Field(alias="startDate")
    next_run_date: datetime = Field(alias="nextRunDate")
    end_date: Optional[datetime] = Field(default=None, alias="endDate")
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    last_run_date: Optional[datetime] = Field(default=None, alias="lastRunDate")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "userId", "name", "amount", "originalCurrency", "originalAmount", "exchangeRate", "accountId", "categoryId", "toAccountId", "transactionType", "frequency", "startDate", "nextRunDate", "endDate", "isActive", "lastRunDate", "createdAt", "updatedAt"]

    @field_validator('original_currency')
    def original_currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"[A-Z]{3}", value):
            raise ValueError(r"must validate the regular expression /[A-Z]{3}/")
        return value

    @field_validator('transaction_type')
    def transaction_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2', '3']):
            raise ValueError("must be one of enum values ('1', '2', '3')")
        return value

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']):
            raise ValueError("must be one of enum values ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecurringTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecurringTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userId": obj.get("userId"),
            "name": obj.get("name"),
            "amount": obj.get("amount"),
            "originalCurrency": obj.get("originalCurrency"),
            "originalAmount": obj.get("originalAmount"),
            "exchangeRate": obj.get("exchangeRate"),
            "accountId": obj.get("accountId"),
            "categoryId": obj.get("categoryId"),
            "toAccountId": obj.get("toAccountId"),
            "transactionType": obj.get("transactionType"),
            "frequency": obj.get("frequency"),
            "startDate": obj.get("startDate"),
            "nextRunDate": obj.get("nextRunDate"),
            "endDate": obj.get("endDate"),
            "isActive": obj.get("isActive"),
            "lastRunDate": obj.get("lastRunDate"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


