# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Transaction(BaseModel):
    """
    Transaction
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: StrictStr
    comments: Optional[StrictStr] = None
    var_date: datetime = Field(alias="date")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    original_currency: StrictStr = Field(alias="originalCurrency")
    original_amount: Union[StrictFloat, StrictInt] = Field(alias="originalAmount")
    exchange_rate: Union[StrictFloat, StrictInt] = Field(alias="exchangeRate")
    account_id: StrictInt = Field(alias="accountId")
    category_id: StrictInt = Field(alias="categoryId")
    is_countable: Optional[StrictInt] = Field(default=None, alias="isCountable")
    linked_transaction_id: Optional[StrictInt] = Field(default=None, alias="linkedTransactionId")
    transaction_type: Optional[StrictInt] = Field(default=None, alias="transactionType")
    __properties: ClassVar[List[str]] = ["id", "name", "comments", "date", "amount", "originalCurrency", "originalAmount", "exchangeRate", "accountId", "categoryId", "isCountable", "linkedTransactionId", "transactionType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "comments": obj.get("comments"),
            "date": obj.get("date"),
            "amount": obj.get("amount"),
            "originalCurrency": obj.get("originalCurrency"),
            "originalAmount": obj.get("originalAmount"),
            "exchangeRate": obj.get("exchangeRate"),
            "accountId": obj.get("accountId"),
            "categoryId": obj.get("categoryId"),
            "isCountable": obj.get("isCountable"),
            "linkedTransactionId": obj.get("linkedTransactionId"),
            "transactionType": obj.get("transactionType")
        })
        return _obj


