# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TransactionPeriodSummaryDTO(BaseModel):
    """
    TransactionPeriodSummaryDTO
    """ # noqa: E501
    total_income: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalIncome")
    total_expense: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalExpense")
    net_total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="netTotal")
    rollover_net: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="rolloverNet")
    net_total_with_rollover: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="netTotalWithRollover")
    transaction_count: Optional[StrictInt] = Field(default=None, alias="transactionCount")
    year: Optional[StrictInt] = None
    month: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["totalIncome", "totalExpense", "netTotal", "rolloverNet", "netTotalWithRollover", "transactionCount", "year", "month"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPeriodSummaryDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPeriodSummaryDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalIncome": obj.get("totalIncome"),
            "totalExpense": obj.get("totalExpense"),
            "netTotal": obj.get("netTotal"),
            "rolloverNet": obj.get("rolloverNet"),
            "netTotalWithRollover": obj.get("netTotalWithRollover"),
            "transactionCount": obj.get("transactionCount"),
            "year": obj.get("year"),
            "month": obj.get("month")
        })
        return _obj


