# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tracko_sdk.models.account import Account
from tracko_sdk.models.category import Category
from tracko_sdk.models.split_detail_dto import SplitDetailDTO
from typing import Optional, Set
from typing_extensions import Self

class TransactionDetailDTO(BaseModel):
    """
    TransactionDetailDTO
    """ # noqa: E501
    id: Optional[StrictInt] = None
    transaction_type: Optional[StrictInt] = Field(default=None, alias="transactionType")
    name: Optional[StrictStr] = None
    comments: Optional[StrictStr] = None
    var_date: Optional[datetime] = Field(default=None, alias="date")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    original_currency: Optional[StrictStr] = Field(default=None, alias="originalCurrency")
    original_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="originalAmount")
    exchange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exchangeRate")
    account_id: Optional[StrictInt] = Field(default=None, alias="accountId")
    category_id: Optional[StrictInt] = Field(default=None, alias="categoryId")
    is_countable: Optional[StrictInt] = Field(default=None, alias="isCountable")
    category: Optional[Category] = None
    account: Optional[Account] = None
    splits: Optional[List[SplitDetailDTO]] = None
    __properties: ClassVar[List[str]] = ["id", "transactionType", "name", "comments", "date", "amount", "originalCurrency", "originalAmount", "exchangeRate", "accountId", "categoryId", "isCountable", "category", "account", "splits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionDetailDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict['category'] = self.category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item in self.splits:
                if _item:
                    _items.append(_item.to_dict())
            _dict['splits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionDetailDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "transactionType": obj.get("transactionType"),
            "name": obj.get("name"),
            "comments": obj.get("comments"),
            "date": obj.get("date"),
            "amount": obj.get("amount"),
            "originalCurrency": obj.get("originalCurrency"),
            "originalAmount": obj.get("originalAmount"),
            "exchangeRate": obj.get("exchangeRate"),
            "accountId": obj.get("accountId"),
            "categoryId": obj.get("categoryId"),
            "isCountable": obj.get("isCountable"),
            "category": Category.from_dict(obj["category"]) if obj.get("category") is not None else None,
            "account": Account.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "splits": [SplitDetailDTO.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None
        })
        return _obj


