# coding: utf-8

"""
    Tracko API

    Expense management REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tracko_sdk.models.user_currency import UserCurrency
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    phone_no: StrictStr = Field(alias="phoneNo")
    email: Optional[StrictStr] = None
    profile_pic: Optional[StrictStr] = Field(default=None, alias="profilePic")
    password: Optional[StrictStr] = None
    global_id: Optional[StrictStr] = Field(default=None, alias="globalId")
    base_currency: Optional[StrictStr] = Field(default=None, alias="baseCurrency")
    is_shadow: Optional[StrictInt] = Field(default=None, alias="isShadow")
    is_admin: Optional[StrictInt] = Field(default=None, alias="isAdmin")
    secondary_currencies: Optional[List[UserCurrency]] = Field(default=None, alias="secondaryCurrencies")
    shadow: Optional[StrictBool] = None
    admin: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "phoneNo", "email", "profilePic", "password", "globalId", "baseCurrency", "isShadow", "isAdmin", "secondaryCurrencies", "shadow", "admin"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in secondary_currencies (list)
        _items = []
        if self.secondary_currencies:
            for _item in self.secondary_currencies:
                if _item:
                    _items.append(_item.to_dict())
            _dict['secondaryCurrencies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "phoneNo": obj.get("phoneNo"),
            "email": obj.get("email"),
            "profilePic": obj.get("profilePic"),
            "password": obj.get("password"),
            "globalId": obj.get("globalId"),
            "baseCurrency": obj.get("baseCurrency"),
            "isShadow": obj.get("isShadow"),
            "isAdmin": obj.get("isAdmin"),
            "secondaryCurrencies": [UserCurrency.from_dict(_item) for _item in obj["secondaryCurrencies"]] if obj.get("secondaryCurrencies") is not None else None,
            "shadow": obj.get("shadow"),
            "admin": obj.get("admin")
        })
        return _obj


