import 'package:tracko/env.dart';

class ConstantUtil {
  static const int SMARTIFY_NOTIFICATION_ID = 124;
  static const int BACKUP_NOTIFICATION_ID = 125;

  static const int MAX_SMS_SCAN_COUNT = 1000;
  static const int MAX_MONTH_SCAN_LIMIT = 4;

  static const String CURRENCY_SYMBOL = "₹ ";
  static const String RUPEE_SIGN = '₹ ';

  static const List<String> CURRENCIES = [
    'AED',
    'AFN',
    'ALL',
    'AMD',
    'ANG',
    'AOA',
    'ARS',
    'AUD',
    'AWG',
    'AZN',
    'BAM',
    'BBD',
    'BDT',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BOB',
    'BRL',
    'BSD',
    'BTN',
    'BWP',
    'BYN',
    'BZD',
    'CAD',
    'CDF',
    'CHF',
    'CLP',
    'CNY',
    'COP',
    'CRC',
    'CUP',
    'CVE',
    'CZK',
    'DJF',
    'DKK',
    'DOP',
    'DZD',
    'EGP',
    'ERN',
    'ETB',
    'EUR',
    'FJD',
    'FKP',
    'GBP',
    'GEL',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'INR',
    'IQD',
    'IRR',
    'ISK',
    'JMD',
    'JOD',
    'JPY',
    'KES',
    'KGS',
    'KHR',
    'KMF',
    'KPW',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LKR',
    'LRD',
    'LSL',
    'LYD',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MMK',
    'MNT',
    'MOP',
    'MRU',
    'MUR',
    'MVR',
    'MWK',
    'MXN',
    'MYR',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NPR',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PHP',
    'PKR',
    'PLN',
    'PYG',
    'QAR',
    'RON',
    'RSD',
    'RUB',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SDG',
    'SEK',
    'SGD',
    'SHP',
    'SLL',
    'SOS',
    'SRD',
    'SSP',
    'STN',
    'SYP',
    'SZL',
    'THB',
    'TJS',
    'TMT',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TWD',
    'TZS',
    'UAH',
    'UGX',
    'USD',
    'UYU',
    'UZS',
    'VES',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XCD',
    'XOF',
    'XPF',
    'YER',
    'ZAR',
    'ZMW',
    'ZWL'
  ];

  static const Map<String, String> currencyToSymbol = {
    'AED': 'د.إ',
    'AFN': '؋',
    'ALL': 'L',
    'AMD': '֏',
    'ANG': 'ƒ',
    'AOA': 'Kz',
    'ARS': '\$',
    'AUD': '\$',
    'AWG': 'ƒ',
    'AZN': '₼',
    'BAM': 'KM',
    'BBD': '\$',
    'BDT': '৳',
    'BGN': 'лв',
    'BHD': '.د.ب',
    'BIF': 'FBu',
    'BMD': '\$',
    'BND': '\$',
    'BOB': 'Bs.',
    'BRL': 'R\$',
    'BSD': '\$',
    'BTN': 'Nu.',
    'BWP': 'P',
    'BYN': 'Br',
    'BZD': 'BZ\$',
    'CAD': '\$',
    'CDF': 'FC',
    'CHF': 'CHF',
    'CLP': '\$',
    'CNY': '¥',
    'COP': '\$',
    'CRC': '₡',
    'CUP': '\$',
    'CVE': '\$',
    'CZK': 'Kč',
    'DJF': 'Fdj',
    'DKK': 'kr',
    'DOP': 'RD\$',
    'DZD': 'د.ج',
    'EGP': '£',
    'ERN': 'Nfk',
    'ETB': 'Br',
    'EUR': '€',
    'FJD': '\$',
    'FKP': '£',
    'GBP': '£',
    'GEL': '₾',
    'GHS': 'GH₵',
    'GIP': '£',
    'GMD': 'D',
    'GNF': 'FG',
    'GTQ': 'Q',
    'GYD': '\$',
    'HKD': '\$',
    'HNL': 'L',
    'HRK': 'kn',
    'HTG': 'G',
    'HUF': 'Ft',
    'IDR': 'Rp',
    'ILS': '₪',
    'INR': '₹',
    'IQD': 'ع.د',
    'IRR': '﷼',
    'ISK': 'kr',
    'JMD': 'J\$',
    'JOD': 'د.ا',
    'JPY': '¥',
    'KES': 'KSh',
    'KGS': 'лв',
    'KHR': '៛',
    'KMF': 'CF',
    'KPW': '₩',
    'KRW': '₩',
    'KWD': 'د.ك',
    'KYD': '\$',
    'KZT': '₸',
    'LAK': '₭',
    'LBP': '£',
    'LKR': 'Rs',
    'LRD': '\$',
    'LSL': 'L',
    'LYD': 'ل.د',
    'MAD': 'د.م.',
    'MDL': 'L',
    'MGA': 'Ar',
    'MKD': 'ден',
    'MMK': 'K',
    'MNT': '₮',
    'MOP': 'MOP\$',
    'MRU': 'UM',
    'MUR': '₨',
    'MVR': 'Rf',
    'MWK': 'MK',
    'MXN': '\$',
    'MYR': 'RM',
    'MZN': 'MT',
    'NAD': '\$',
    'NGN': '₦',
    'NIO': 'C\$',
    'NOK': 'kr',
    'NPR': '₨',
    'NZD': '\$',
    'OMR': 'ر.ع.',
    'PAB': 'B/.',
    'PEN': 'S/.',
    'PGK': 'K',
    'PHP': '₱',
    'PKR': '₨',
    'PLN': 'zł',
    'PYG': 'Gs',
    'QAR': 'ر.ق',
    'RON': 'lei',
    'RSD': 'дин',
    'RUB': '₽',
    'RWF': 'R₣',
    'SAR': 'ر.س',
    'SBD': '\$',
    'SCR': '₨',
    'SDG': 'ج.س.',
    'SEK': 'kr',
    'SGD': '\$',
    'SHP': '£',
    'SLL': 'Le',
    'SOS': 'S',
    'SRD': '\$',
    'SSP': '£',
    'STN': 'Db',
    'SYP': '£',
    'SZL': 'E',
    'THB': '฿',
    'TJS': 'SM',
    'TMT': 'T',
    'TND': 'د.ت',
    'TOP': 'T\$',
    'TRY': '₺',
    'TTD': 'TT\$',
    'TWD': 'NT\$',
    'TZS': 'TSh',
    'UAH': '₴',
    'UGX': 'USh',
    'USD': '\$',
    'UYU': '\$U',
    'UZS': 'лв',
    'VES': 'Bs.S',
    'VND': '₫',
    'VUV': 'VT',
    'WST': 'WS\$',
    'XAF': 'FCFA',
    'XCD': '\$',
    'XOF': 'CFA',
    'XPF': '₣',
    'YER': '﷼',
    'ZAR': 'R',
    'ZMW': 'ZK',
    'ZWL': 'Z\$'
  };

  static String getCurrencySymbol(String currencyCode) {
    return currencyToSymbol[currencyCode] ?? currencyCode;
  }

  static const bool DISABLE_SCANNING_MONTH_LIMIT = true;

  static const String AUTO_BACK_UP_KEY = "autoBackUp";
  static const String AUTO_BACK_UP_TIMESTAMP_KEY = "autoBackUpTimeStamp";
  static const String LAST_READ_SMS_ID = "lastReadSmsId";

  static const int NO_OF_RECORDS_PER_PAGE = 25;

  static const String version = Environment.appVersion;
}
