#logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.liquibase = INFO
liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.profiles.active=dev
#spring.jackson.serialization.fail-on-empty-beans=false
hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
jwt.secret=tracko_jwt_secret_change_me_to_32+_chars_min