# PostgreSQL Configuration for Production
spring.datasource.url=${JDBC_URL:jdbc:postgresql://localhost:5432/expense_manager}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Server Configuration
server.port=${PORT:8080}

# Logging Configuration
logging.level.liquibase=info
