

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
logging.level.liquibase = INFO
liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.default-schema=SYSTEM
liquibase.default-schema=SYSTEM