spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
logging.level.liquibase = INFO
spring.profiles.active=dev
spring.liquibase.default-schema=SYSTEM
liquibase.default-schema=SYSTEM